# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/OR_Gate.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/MUX_3_1.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/AND_Gate.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/Full_Adder.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/ALU.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/PC_Register.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/Sign_Extend.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/Registers.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/MUX_2_1.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/Memory.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/Control.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/ALU_16bit.vhd}
  {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado 2016.3 Projects/ENGG3380_Project/ENGG3380_Project.srcs/sources_1/new/CPU.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU -part xc7a100tcsg324-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
