-- Copyright 1986-2016 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2016.3 (win64) Build 1682563 Mon Oct 10 19:07:27 MDT 2016
-- Date        : Mon Apr 01 20:23:09 2024
-- Host        : Steven-Spectre running 64-bit major release  (build 9200)
-- Command     : write_vhdl -mode funcsim -nolib -force -file {C:/Users/Steven Shelestowsky/OneDrive/Documents/Vivado
--               2016.3 Projects/ENGG3380_Project/ENGG3380_Project.sim/sim_1/synth/func/CPU_Test_func_synth.vhd}
-- Design      : CPU
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7a100tcsg324-1
-- --------------------------------------------------------------------------------
